### PR TITLE
Update README.md with Youtube link

### PR DESCRIPTION
**Pull request by ShalokShalom**
This adds a Youtube video including preview

### CODE REVIEW

**Review by manuq — COMMENTED** [review]
Thanks! That video shows a very old version of the plugin. But maybe it's better than nothing?

**Review by manuq — APPROVED** [review]

**Comment by manuq** [comment]
Let's merge this for now. We can update the README with a new video later.

**Comment by ShalokShalom** [comment]
Lets raise an issue about making a new video

**Comment by manuq** [comment]
@ShalokShalom here is a more up-to-date video: https://www.youtube.com/watch?v=Dv7cKDdNu1o

It's different, a very short overview without any explanation. Then there is also the GodotCon 2024 presentation: https://www.youtube.com/watch?v=EJDNYFha9GY

**Pull request merged**
