### PR TITLE
Add vector3

### PR DESCRIPTION
**Pull request by urbit-pilled**
/claim #330 

I added Vector3 support to parameter_input and blocks_catalog.

### CODE REVIEW

**Comment by manuq** [comment]
Good start! I can add Block Code to a Node3D and see the Vector3 input of position, rotation, scale. Now when I try to add some numbers for the X, Y, Z I see errors in the output:
```
  res://addons/block_code/ui/blocks/utilities/parameter_input/parameter_input.gd:173 - Invalid access to property or key 'V3XLineEdit:<LineEdit#2924352752547>' on a base object of type 'Dictionary'.
  res://addons/block_code/ui/blocks/utilities/parameter_input/parameter_input.gd:173 - Invalid access to property or key 'V3YLineEdit:<LineEdit#2924587633585>' on a base object of type 'Dictionary'.
  res://addons/block_code/ui/blocks/utilities/parameter_input/parameter_input.gd:173 - Invalid access to property or key 'V3ZLineEdit:<LineEdit#2924822514623>' on a base object of type 'Dictionary'.
```

**Comment by urbit-pilled** [comment]
@manuq fixed in bba1d22

**Review by manuq — APPROVED** [review]
This is working very well now!
[Grabación de pantalla desde 2024-12-17 09-03-13.webm](https://github.com/user-attachments/assets/c622930a-832e-4a4d-b3b3-339a56011bd5)

As last thing, could you add some blocks for Vector3 handling? Like these ones for Vector2:
Captura desde 2024-12-17 09-05-51

Basically:
- Blocks for obtaining the Vector3 components (x, y, z).
- A block for composing a Vector3 with 3 components.

Then it's good to merge.

**Comment by urbit-pilled** [comment]
Ok, just added the new blocks in e2e7397 @manuq

**Review by manuq — APPROVED** [review]
The new blocks look good! As with the previous PR, please rebase into one or multiple commits with descriptive commit messages.

**Comment by urbit-pilled** [comment]
just squashed the commits, should be ready to merge now.

**Comment by manuq** [comment]
The blocks for Vector3 operations are working!
[Grabación de pantalla desde 2024-12-17 13-34-32.webm](https://github.com/user-attachments/assets/e1ac85be-0cd6-4e58-9ec0-60550f22e46b)

**Pull request merged**
