### PR TITLE
Context menu, delete, duplicate, and pin function

### PR DESCRIPTION
**Pull request by DoomTas3r**
Adds a context menu with 4 functions: duplicate, summary, pin, and delete

Adds a duplicate function with `ctrl + d` as a shortcut as suggested by https://github.com/endlessm/godot-block-coding/issues/201#issuecomment-2422916623 and https://github.com/endlessm/godot-block-coding/issues/267#issue-2582213586. The offset is 100 pixels right, 50 pixels down. The snapped blocks and parameter values are also duplicated

The summary shows the tooltip of the block, intended to be replaced by a more detailed overview like https://github.com/endlessm/godot-block-coding/pull/291#issue-2613021742

Adds a pin function with `ctrl + p` as a shortcut. Pinned blocks can't be dragged. Snapped blocks can pin with their parent block. This feature doesn't need to be added because the undo feature can undo the effects of accidental drags or deletes, so this is just for convenience

`_confirm_delete` is its own function

Functions that check snapped blocks only check `Container` nodes because only they have `SnapPoint` nodes

When the drag drop area receives a right click, a new popup menu determines which function is called from the parent block
image
image

### CODE REVIEW

**Comment by manuq** [comment]
@DoomTas3r thanks! There is a bounty for the duplicate functionality. Please follow the steps in https://github.com/endlessm/godot-block-coding/issues/201#issuecomment-2433252534 if you would like to attempt it.

**Comment by DoomTas3r** [comment]
Thanks, but I will not accept or claim the bounty

**Comment by manuq** [comment]
@DoomTas3r I see that you are trying to add pin functionality to this PR as well, which was never discussed. My suggestion is to try contributing smaller chunks, because they are more likely to be merged. For example I would start with a context menu and just the current Delete functionality that is already there (as Del key shortcut).

**Comment by manuq** [comment]
@DoomTas3r the Duplicate and Delete has been merged. If you still want to discuss pin functionality, please open a issue. Closing this for now!

**Pull request closed without merging**
