### PR TITLE
Add context menu with duplicate

### PR DESCRIPTION
**Pull request by urbit-pilled**
/claim #201 

modified #293 so that it only contains the duplication feature. (removed pin, summary, and delete functionality)

https://github.com/user-attachments/assets/cfd9976d-50b2-4f38-b152-db3900217635

### CODE REVIEW

**Comment by urbit-pilled** [comment]
I saw that it wasn't even compiling so I don't think you've made enough effort to lock this issue. @varshith257.

**Comment by urbit-pilled** [comment]
Right, but now its finished after mine. (Not that it was much work as most of it was done by @DoomTas3r)

**Comment by urbit-pilled** [comment]
I don't ever open a PR that someone else is already working on unless I think that they haven't made a good effort in their PR.

That's why I opened the PR. (Because a PR that doesn't compile means that you haven't even run in on your own computer yet)

**Comment by DoomTas3r** [comment]
@urbit-pilled Nice, although some requested features from [this proposal](https://github.com/endlessm/godot-block-coding/issues/201#issuecomment-2422916623) were left out, most notably the Ctrl-D shortcut to Duplicate.

**Comment by urbit-pilled** [comment]
It was a bit ambiguous to me what @manuq wanted because later on he said that the other things should be discussed first.
but I think you're right @DoomTas3r, I think he was referring to the pin and summary when he was talking about features that need discussing first.

I have added back the Ctrl + d shortcut and added Delete to the dropdown menu.

**Comment by manuq** [comment]
Thanks @urbit-pilled . I squashed the commits and took the liberty to improve the commit message in #345, while still giving credit to the original author @DoomTas3r. Thanks both.

**Pull request closed without merging**
